### ISSUE TITLE
How to use it

### ISSUE THREAD

**Issue by alvinahayward** [xs0521/GithubNote#1]
<img width="794" alt="image" src="https://github.com/user-attachments/assets/6e173857-e2cb-452b-a34a-f2fe5d0f4737" />
I got this error as in the screenshot. Can you explain how to use the software? thank you, like how to make a workspace

**Comment by xs0521** [comment]
**First of all, thank you for using it**

 The top menu bar -> Edit

<img width="234" alt="Xnip2024-12-21_09-54-38" src="https://github.com/user-attachments/assets/c5ac308c-f6c4-41bd-aa6f-6ae215e01d5a" />

When display workspace, click plus icon

<img width="358" alt="Xnip2024-12-21_09-56-36" src="https://github.com/user-attachments/assets/aa641b42-b6f8-4f42-97bc-0073dee70503" />


Feel free to contact me if you have any questions

**Comment by alvinahayward** [comment]
thanks
